"use client";

import { useEffect, useRef, useState, type KeyboardEvent } from "react";

const commands = ["help", "about", "projects", "experience", "education", "skills", "contact", "resume", "github", "clear", "neofetch", "theme", "history", "pwd", "ls"];
const projects = [
  {name:"bik", label:"A language, from scratch.", tech:"C · MIPS Assembly · CMake", description:"A compiler that turns a custom high-level language into MIPS assembly. Lexer, recursive-descent parser, scoped AST, and constant folding included.", tag:"01 / SYSTEMS"},
  {name:"SpringForge", label:"Making the math move.", tech:"Python · VPython · Calculus", description:"A configurable spring-system simulator with nonlinear torque, numerical integration, and a polygon editor that calculates center of mass and inertia.", tag:"02 / SIMULATION"},
  {name:"Slipstream", label:"Built for the next lap.", tech:"Java · Processing · Networking", description:"A multiplayer racer with real-time state synchronization, terrain-aware physics, drifting, nitro, and pixel-based collisions.", tag:"03 / GAMES"},
  {name:"ascii", label:"Pixels meet the terminal.", tech:"Python · ASCII", description:"Convert videos into ASCII and watch them play right in the terminal. Yes, including Bad Apple.", tag:"04 / EXPERIMENTS"},
];
type Entry = {command:string; kind:string; text?:string};
function Prompt({command}:{command?:string}) { return <div className="prompt"><span className="green">visitor</span><span className="muted">@</span><span className="green">owen</span><span className="muted">:</span><span className="purple">~</span><span className="dollar">$</span>{command && <span className="command-text">{command}</span>}</div>; }
function External({href,children}:{href:string;children:React.ReactNode}){return <a href={href} target="_blank" rel="noreferrer">{children} <span aria-hidden="true">↗</span></a>}
function Output({entry,run}:{entry:Entry;run:(s:string)=>void}) {
  if(entry.kind==="welcome") return <div className="welcome"><div className="boot"><span className="green">[ OK ]</span> A little corner of the internet, built from curiosity.</div><div className="identity"><pre className="ascii" aria-hidden="true">{` ██████╗ ██╗    ██╗███████╗███╗   ██╗
██╔═══██╗██║    ██║██╔════╝████╗  ██║
██║   ██║██║ █╗ ██║█████╗  ██╔██╗ ██║
██║   ██║██║███╗██║██╔══╝  ██║╚██╗██║
╚██████╔╝╚███╔███╔╝███████╗██║ ╚████║
 ╚═════╝  ╚══╝╚══╝ ╚══════╝╚═╝  ╚═══╝`}</pre><div className="identity-meta"><span className="mini-label">HELLO, WORLD. I’M</span><h1>Owen Shi<span className="green">.</span></h1><span className="handle">@Bi1ku</span><div className="palette"><i/><i/><i/><i/><i/><i/></div></div></div><p className="intro">Computer science & mathematics at <span className="cream">Harvard.</span><br/>Building things from the metal up—and occasionally making them drift.</p><div className="interests"><span>systems programming</span><span>robotics</span><span>full-stack development</span></div><p className="tip">Welcome to my interactive portfolio.<br/>Type <button onClick={()=>run("help")}>help</button> to explore, or pick a command below.</p><div className="quick-commands">{["about","projects","experience","contact"].map(c=><button onClick={()=>run(c)} key={c}><span className="green">./</span>{c}<span className="shortcut-arrow">↵</span></button>)}</div></div>;
  if(entry.kind==="projects") return <div className="output"><div className="section-label">SELECTED PROJECTS <span>4 directories</span></div><div className="projects">{projects.map(p=><article key={p.name}><div className="project-tag">{p.tag}</div><h3><External href={`https://github.com/Bi1ku/${p.name}`}>{p.name}</External></h3><p className="project-label">{p.label}</p><p>{p.description}</p><div className="tech">{p.tech}</div></article>)}</div><p className="footnote">More experiments, dotfiles, and works in progress on <External href="https://github.com/Bi1ku?tab=repositories">GitHub</External>.</p></div>;
  if(entry.kind==="about"||entry.kind==="neofetch") return <div className="output"><h2>Owen Shi <span className="muted">/ about.txt</span></h2><p>I’m a Harvard College freshman studying Computer Science & Mathematics, originally from Queens, New York, and a Stuyvesant High School graduate.</p><p>My work spans compilers, autonomous robots, physics simulations, and web applications. I like getting under the hood: from turning source code into MIPS assembly to getting a robot to find its way around a field.</p><dl><dt>based in</dt><dd>Queens, NY / Cambridge, MA</dd><dt>on GitHub</dt><dd><External href="https://github.com/Bi1ku">@Bi1ku</External></dd><dt>toolbox</dt><dd>Neovim, C, Python, TypeScript, and a healthy amount of curiosity</dd></dl></div>;
  if(entry.kind==="experience") return <div className="output"><h2>Experience <span className="muted">/ the work so far</span></h2><div className="timeline"><article><div className="date">SEP 2023 — JUL 2026</div><h3>Stuy Fusion · FTC 479</h3><p className="green">Vice President</p><p>Built AprilTag localization and autonomous alignment, multithreaded controls running at 10 kHz, and a reusable command-based architecture. Developed the team website and taught workshops across a team of ~32 members.</p></article><article><div className="date">FEB 2022 — SEP 2025</div><h3>BCTCio</h3><p className="green">Full-Stack Web Developer Intern</p><p>Built full-stack web features and maintained a UI library with 30+ production-ready components. Helped develop Future Sphere Education’s portal for 4,000+ active students, 300+ classes, and 12+ teachers.</p></article><article><div className="date">JUN — SEP 2024</div><h3>NYC Department of Health and Mental Hygiene</h3><p className="green">Information Technology Specialist Intern</p><p>Supported recovery across 3,000+ computers following the CrowdStrike outage and imaged 62 PCs. Upgraded workstations and audited hardware inventory.</p></article></div></div>;
  if(entry.kind==="education") return <div className="output"><h2>Education</h2><h3>Harvard College</h3><p>Freshman · B.A. in Computer Science & Mathematics · Cambridge, MA</p><h3>Stuyvesant High School</h3><p>Advanced Regents Diploma · Manhattan, NY</p><p className="green">SAT 1570 / 800 Math · GPA 97.45</p></div>;
  if(entry.kind==="skills") return <div className="output"><h2>What’s in the toolbox?</h2><dl><dt>languages</dt><dd>C, C++, Java, Kotlin, Lua, Go, JavaScript, TypeScript, Python</dd><dt>web</dt><dd>React, Next.js, Node.js, HTML, CSS, Tailwind CSS, Material UI</dd><dt>data & cloud</dt><dd>PostgreSQL, Prisma, MongoDB, Supabase, AWS, Google Cloud</dd><dt>tools</dt><dd>Neovim, VS Code, Android Studio, CMake</dd><dt>human languages</dt><dd>English (fluent), Spanish (intermediate), Mandarin Chinese (conversant)</dd></dl></div>;
  if(entry.kind==="contact") return <div className="output"><h2>Let’s build something.</h2><p>Have a project, an interesting problem, or just want to say hi?</p><div className="contact-links"><a href="mailto:2008owenshi@gmail.com">2008owenshi@gmail.com ↗</a><External href="https://github.com/Bi1ku">github.com/Bi1ku</External></div></div>;
  if(entry.kind==="resume") return <div className="output"><h2>The one-page version.</h2><p>Education, experience, projects, and skills in a single PDF.</p><a className="download" href="/Owen_Shi_Resume.pdf" download>↓ Download my resume</a></div>;
  if(entry.kind==="github") return <div className="output"><External href="https://github.com/Bi1ku">Explore @Bi1ku on GitHub</External></div>;
  if(entry.kind==="help") return <div className="output"><h2>A small field guide.</h2><p>Click a command or type it at the prompt.</p><div className="help-grid">{[["about","A little about me"],["projects","Things I’ve built"],["experience","Where I’ve worked"],["education","Where I’m learning"],["skills","My toolbox"],["contact","Get in touch"],["resume","Download the PDF"],["github","Explore my repositories"],["clear","A fresh terminal"],["theme","Switch green / amber"],["history","Your command history"],["neofetch","System info, Owen edition"]].map(([c,d])=><button key={c} onClick={()=>run(c)}><span>{c}</span><span>{d}</span></button>)}</div><p className="footnote">↑ ↓ history · Tab autocomplete · Ctrl+L clear · Ctrl+C cancel</p></div>;
  return <pre className="plain-output">{entry.text}</pre>;
}
export default function Home(){
  const [entries,setEntries]=useState<Entry[]>([{command:"./welcome.sh",kind:"welcome"}]);
  const [value,setValue]=useState(""); const [history,setHistory]=useState<string[]>([]); const [historyIndex,setHistoryIndex]=useState(-1); const [amber,setAmber]=useState(false); const [active,setActive]=useState("home");
  const input=useRef<HTMLInputElement>(null); const bottom=useRef<HTMLDivElement>(null); const initial=useRef(true);
  useEffect(()=>{if(initial.current){initial.current=false;return;}bottom.current?.scrollIntoView({behavior:"smooth",block:"nearest"});},[entries]);
  function run(raw:string){const command=raw.trim();if(!command)return;const key=command.toLowerCase().replace(/^\.\//,"");setHistory(h=>[...h,command]);setHistoryIndex(-1);setValue("");let entry:Entry={command,kind:key};
    if(key==="clear"){setEntries([]);setActive("clear");input.current?.focus({preventScroll:true});return;}
    if(key==="home"||key==="welcome"||key==="welcome.sh")entry.kind="welcome";
    else if(key==="ls"||key==="ls -la")entry={command,kind:"text",text:"about.txt   projects/   experience/   education.txt   skills.txt   contact.txt   resume.pdf"};
    else if(key.startsWith("cat ")){const file=key.slice(4).replace(/\.(txt|pdf)$/,"");entry=commands.includes(file)?{command,kind:file}:{command,kind:"text",text:`cat: ${key.slice(4)}: No such file. Try ls.`};}
    else if(key==="pwd")entry.text="/home/owen";
    else if(key==="history")entry.text=[...history,command].map((h,i)=>`${String(i+1).padStart(3)}  ${h}`).join("\n");
    else if(key==="theme"){setAmber(!amber);entry.text=`Theme switched to ${amber?"phosphor green":"warm amber"}.`;}
    else if(key==="whoami")entry={command,kind:"text",text:"visitor — make yourself at home."};
    else if(key==="sudo"||key.startsWith("sudo "))entry={command,kind:"text",text:"Nice try. You’re already welcome here; no elevated privileges needed."};
    else if(!commands.includes(key)&&entry.kind!=="welcome")entry={command,kind:"text",text:`command not found: ${command}\nType help to see what’s available.`};
    setEntries(e=>[...e,entry]);setActive(entry.kind);input.current?.focus({preventScroll:true});
  }
  function onKey(e:KeyboardEvent<HTMLInputElement>){if(e.key==="ArrowUp"){e.preventDefault();const next=historyIndex<0?history.length-1:Math.max(0,historyIndex-1);setHistoryIndex(next);setValue(history[next]||"");}else if(e.key==="ArrowDown"){e.preventDefault();const next=historyIndex+1;if(historyIndex<0||next>=history.length){setHistoryIndex(-1);setValue("");}else{setHistoryIndex(next);setValue(history[next]);}}else if(e.key==="Tab"){e.preventDefault();const found=commands.filter(c=>c.startsWith(value.toLowerCase()));if(found.length===1)setValue(found[0]);else if(found.length>1)setEntries(es=>[...es,{command:value,kind:"text",text:found.join("  ")}]);}else if(e.ctrlKey&&e.key==="l"){e.preventDefault();run("clear");}else if(e.ctrlKey&&e.key==="c"){e.preventDefault();setValue("");}}
  return <div className={amber?"desktop amber":"desktop"}><header className="desktop-bar"><a className="brand" href="#" onClick={e=>{e.preventDefault();run("home")}}><span className="brand-symbol">&gt;_</span> owen<span className="muted">.shi</span></a><div className="desktop-center">personal workspace</div><div className="desktop-right"><span className="status-dot"/>Harvard · CS + Math</div></header><main><div className="workspace-heading"><span><span className="green">~</span> / home / owen</span><span className="muted">a work in progress, like its author.</span></div><section className="terminal" aria-label="Interactive portfolio terminal"><div className="titlebar"><div className="window-dots" aria-hidden="true"><i/><i/><i/></div><span>visitor@owen: ~</span><span className="shell-label">zsh</span></div><div className="terminal-layout"><aside><div className="explorer-label">EXPLORER</div><button className={active==="home"||active==="welcome"?"selected":""} onClick={()=>run("home")}><span>⌂</span> ~/owen</button><div className="tree">{["about","projects","experience","education","skills","contact"].map(c=><button className={active===c?"selected":""} key={c} onClick={()=>run(c)}><span className={c==="projects"?"purple":"muted"}>{c==="projects"||c==="experience"?"▸":"≡"}</span>{c}{c==="projects"||c==="experience"?"/":".txt"}</button>)}</div><button onClick={()=>run("resume")}><span className="peach">↓</span> resume.pdf</button><div className="aside-bottom"><span className="status-dot"/> always curious<br/><span className="muted">made of code & coffee</span></div></aside><div className="terminal-pane"><div className="terminal-scroll"><div className="session-line">OWEN’S PERSONAL SHELL <span>v1.0.0</span></div>{entries.map((entry,i)=><section className="entry" key={i}><Prompt command={entry.command}/><Output entry={entry} run={run}/></section>)}<form className="command-form" onSubmit={e=>{e.preventDefault();run(value)}}><label htmlFor="terminal-input" className="sr-only">Enter a portfolio command</label><Prompt/><input id="terminal-input" ref={input} value={value} onChange={e=>setValue(e.target.value)} onKeyDown={onKey} placeholder="type a command…" autoComplete="off" autoCapitalize="none" spellCheck={false}/><button type="submit" aria-label="Run command">↵</button></form><div ref={bottom}/></div><div className="terminal-status"><span><b> NORMAL </b><span className="green"> ⎇ </span> main</span><span>UTF-8 <span className="muted">│</span> interactive portfolio</span></div></div></div></section><footer><span>Not a real shell. Just a real person who likes them.</span><div><button onClick={()=>{input.current?.focus();run("help")}}>help</button><a href="https://github.com/Bi1ku" target="_blank" rel="noreferrer">GitHub ↗</a><a href="mailto:2008owenshi@gmail.com">Say hello ↗</a></div></footer></main></div>;
}
